### ISSUE TITLE
Implement daylight savings time

### ISSUE THREAD

**Issue by laviealon** [pinnymz/python-zmanim#12]

**Comment by pinnymz** [comment]
@laviealon this library depends on [python-dateutil for TimeZone support](https://dateutil.readthedocs.io/en/stable/tz.html).  Every TimeZone includes the relevant DST rules. So if you supply the TimeZone to the calculator as part of GeoLocation, it will handle DST for you - see [the README](https://github.com/pinnymz/python-zmanim/blob/master/README.md) for an example in code, and see [here](https://github.com/pinnymz/python-zmanim/blob/master/zmanim/astronomical_calendar.py#L109) where this conversion is done.
