### ISSUE TITLE
Add 'limudim' module to pypi package

### ISSUE THREAD

**Issue by benyaming** [pinnymz/python-zmanim#7]
Hi
There is [limudim module](https://github.com/pinnymz/python-zmanim/tree/master/zmanim/limudim)
But if I install package via pypi, this module is missing. Could you please bump pack version with this module? 
Thank you a lot!

**Comment by pinnymz** [comment]
There is a performance issue with some of the limudim calculations that I was hoping to address before release.  I'll post back when the package is updated.

**Comment by benyomin94** [comment]
Are you planning to release soon? I mean, should I wait some time for it, or just fork your repo to my code?

**Comment by pinnymz** [comment]
Can't say how long at this point, so forking is probably your best bet right now.

**Comment by jacobshilitz** [comment]
I'm planning to use the _limudim_ to get the _parsha_ will my performance be affected?

PS. it can also be installed from git via pip

```
pip install git+https://github.com/pinnymz/python-zmanim.git
```

or add in requirements.txt
```
git+https://github.com/pinnymz/python-zmanim.git
```

**Comment by pinnymz** [comment]
@jacobshilitz performance isn't really an issue for recurring limudim like parsha, only for time anchored limudim like daf yomi.  Even then, the performance issue may not be a significant problem depending on your usage.  It just isn't fast enough for my liking :)

**Comment by pinnymz** [comment]
@benyaming @jacobshilitz this has now been released

**Comment by clippycoder** [comment]
@pinnymz, would you be able to add a guide to limudim calculations to the readme? I can't figure out how to use them.

**Comment by pinnymz** [comment]
@clippycoder not a bad idea.  Do you have another particular limud that you're interested in?  While working on it, I'll see if I can come up with a semi-formal process to develop a wiki walkthrough.

**Comment by clippycoder** [comment]
Personally I was interested in the Daf Yomi module. After enough poking around (I'm new to python) I was able to get it to work! However I wanted it to be in hebrew so I used [this project](https://github.com/danyeric123/DafYomiAndMore/blob/main/main.py) and just replaced the text.
