### ISSUE TITLE
JewishDate Go back Error

### ISSUE THREAD

**Issue by ari-github** [pinnymz/python-zmanim#9]
When `jd.back()` is called and it needs to go a year back
like this:
`jd = JewishDate(5781, 1, 1)`
`jd.back()`
or
`jd.forward(-1)`

I get an error

> m = days_of_year.length
> AttributeError: 'list' object has no attribute 'length'

**Comment by pinnymz** [comment]
@ari-github thanks for reporting this!  Fixed with https://github.com/pinnymz/python-zmanim/commit/dc7ff798a7d9af5f7f0697a18520bdb0292eac92, will hopefully get a patch release out shortly.

**Comment by pinnymz** [comment]
Pushed out https://pypi.org/project/zmanim/0.3.1/ just now, @ari-github please confirm if you are seeing correct behavior now.

**Comment by ari-github** [comment]
Yes it worked
Thank you!
